stages:
- name: Build
  steps:
  - runScriptConfig:
      image: lawr/maven:3-jdk-7
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      DOCKER_HOST: tcp://dind.default:2379
      PLUGIN_DAEMON_OFF: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
