stages:
- name: Build
  steps:
  - runScriptConfig:
      image: lawr/maven:3-jdk-7-cached
      shellScript: mvn -s /usr/share/maven/ref/settings-docker.xml clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
